output "project_name" {
  description = "Name of the sample project."
  value       = local.project_name
}

output "common_tags" {
  description = "Common tags generated by the example."
  value       = local.common_tags
}